[tool.poetry]
name = "chat_app"
version = "0.1.0"
description = ""
authors = ["Gipss <gissa.dmtr@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.11"
flet = "^0.3.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
